services:
  localstack:
    image: localstack/localstack:4.4.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs,s3,sns
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - type: bind
        source: ./init-localstack.sh
        target: /etc/localstack/init/ready.d/init-aws.sh
        read_only: true
    networks:
      - workshop-network

networks:
  workshop-network:
    driver: bridge