spring.application.name: spring-cloud-aws-workshop

spring:
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      endpoint: http://localhost:4566
      s3:
        path-style-access-enabled: true
